# Github Version, please remove _hub from the yaml file and 
# provide your keys and secrets 
CONSUMER_KEY: 'Specify your Keys here'
CONSUMER_SECRET: 'Specify your Keys here'
ACCESS_TOKEN: 'Specify your Keys here'
ACCESS_TOKEN_SECRET: 'Specify your Keys here'
