CONSUMER_KEY: 'tDLE1thCzB19Xd6wvQTvtg4Yt'
CONSUMER_SECRET: 'ceKs1bSyaCFrtwKWDRt24Ol5GMjKbNaEdE5b0Hws9A0fHGLkA9'
ACCESS_TOKEN: '979456159978545152-Az5LQ0olYXkxCKxrdOuj3URq8tfsrYQ'
ACCESS_TOKEN_SECRET: 'QYQNopu5nA1m5BaWf6KE6UnlFF0UJIqnHQV5SoQr6Dxij'
